"""Initial revision

Revision ID: 43537e827107
Revises: 
Create Date: 2026-03-23 10:07:45.149830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '43537e827107'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute("CREATE SCHEMA IF NOT EXISTS documents")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.TEXT(), nullable=False),
    sa.Column('file_hash', sa.TEXT(), nullable=True),
    sa.Column('file_path', sa.TEXT(), nullable=True),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_link', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='documents'
    )
    op.create_table('document_vectors',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('document_uid', sa.Uuid(), nullable=False),
    sa.Column('metadata_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_uid'], ['documents.documents.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    schema='documents'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_vectors', schema='documents')
    op.drop_table('documents', schema='documents')

    op.execute("DROP SCHEMA IF EXISTS documents")
    # ### end Alembic commands ###
